name: Deploy
on:
  push:
    branches:
      - main
# permissions: read-all|write-all
jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        
      - name: Build
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
