name: Deploy
on:
  push:
    branches:
      - main
permissions: read-all|write-all
jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # option
          
      - name: Checkout public repo
        uses: actions/checkout@v2
        with:
          repository: wdh99/wdh99.github.io
          ref: gh-pages
          path: site
        
      - name: Copy To Public Repo
        run: cp -r page-action/site/* wdh99.githu.io/site
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
