site_name: WDH99
site_url: https://wdh99.github.io/  # 回到首页
# nav:
#   - Home: '../' # 回到网站上一级
repo_url: https://github.com/wdh99/

# copyright: WuDingHuan
#pymdownx-material 的文档:https://pypi.org/project/mkdocs-pymdownx-material-extras/
theme:
  name: material
  custom_dir: custom_theme
  language: 'zh'
  pymdownx:
      sponsor: "" #赞助链接
  # palette:
    # scheme: dracula # This is how to enables the Dracula theme for dark. For light, it will use default Material with some tweaks.
    # primary: amber # Primary colors
    # accent: amber # accent color
  feature:
    tabs: true  # 横向导航(true和false没看出变化)
watch: # 指定监视变化的内容
- docs
- mkdocs.yml

plugins:
  - search
  - mkdocs_pymdownx_material_extras # 深色与浅色主题切换
  #- i18n:
  #    default_language: zn_CN
  - encryptcontent:
      # global_password: 'your_password'
      translations:
        zh_CN:
          placeholder: '666'
          encryption_info_message: '1'
          decryption_failure_message: '2'
          password_button_text: '3'
          title_prefix: '4'
          summary: '5'

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        # Mermaid diagrams
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - pymdownx.betterem
  #- pymdownx.betterem:  # 对加粗和斜体更好的检测
  #    smart_enable: all
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
  - pymdownx.arithmatex  # 数学公式
  - pymdownx.emoji:  # 表情
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

extra_javascript:
  - 'tongji/baidu-tongji.js' # 自定义个每个页面加入百度统计
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js
